name = "hexxytest3"
author = "chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3b4ad328144c3037103400c050e69686e2843a2ab84aef67473099757536606"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
